---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: debian-8.2
  - name: centos-7.1
  - name: fedora-22

suites:
  - name: default
    run_list:
      - recipe[tutum::default]
    attributes:
